/**
 * Chunk metadata: the small per-chunk "metadata" tags a real 1.26 world writes
 * on every chunk, and the global dictionary they point into.
 *
 * A phone-native 1.26.51 export carries three extra records per chunk:
 *
 *   MetaDataHash        (0x3F)  uint64 LE — key into the dictionary below
 *   BlendingData        (0x40)  uint8 "used for blending" + uint8 blend version
 *                               (+ int16[16] heights + uint8 neighbours when
 *                               the first byte is 1; we are never a blending
 *                               source, so it stays `[0, version]`)
 *   ActorDigestVersion  (0x41)  uint8 — entity-digest format, 0 = 1.18.30
 *
 * `MetaDataHash` is the xxHash64 (seed 0) of the chunk's metadata NBT, which is
 * stored once in the world-level `LevelChunkMetaDataDictionary` record:
 *
 *   uint32 LE entry count
 *   { uint64 LE hash, NBT compound } * count
 *
 * Both the hash and the dictionary were reverse-engineered in Prismarine-Anchor
 * (`level_chunk_meta_data_dictionary.rs`, `metadata_hash.rs`), whose parser
 * rejects real worlds unless the hash matches, i.e. the game hashes the
 * *network-order* serialization (little-endian with varint i32/i64 and varint
 * string lengths) of the compound with its keys recursively sorted. That is
 * exactly what `hashChunkMetaData` reproduces here. The metadata fields are the
 * ones the Minecraft Wiki documents for `MetaDataHash`.
 *
 * Every field is set to "this world is already current and already upgraded",
 * so a client that reads the metadata has no migration left to perform.
 */

import { ByteWriter, TAG } from "./nbt-le.ts";

/** World-level LevelDB key holding the metadata dictionary. */
export const METADATA_DICTIONARY_KEY = "LevelChunkMetaDataDictionary";

/** Only digest format Bedrock has shipped: v1_18_30. */
export const ACTOR_DIGEST_VERSION = 0;

/** BlendingData / MetaData.BlendingVersion: 8 = v1_21_100, the newest known. */
export const BLENDING_VERSION = 8;

/** A lightweight NBT tag tree — enough for the metadata compound. */
export type MetaTag =
  | { kind: "string"; value: string }
  | { kind: "bool"; value: boolean }
  | { kind: "short"; value: number }
  | { kind: "int"; value: number }
  | { kind: "long"; value: bigint }
  | { kind: "compound"; value: Record<string, MetaTag> };

export interface ChunkMetaDataInput {
  /** Base game version string, e.g. "1.26.51". */
  baseGameVersion: string;
  /** World generation seed. */
  generationSeed: bigint;
  /** level.dat `Generator`: 0 old, 1 infinite, 2 flat. */
  generatorType: number;
  /** Dimension this chunk belongs to ("Overworld"). */
  dimensionName: string;
  /** Dimension height envelope, e.g. { min: -64, max: 320 }. */
  dimensionRange: { min: number; max: number };
}

/**
 * Values usable as-is for this reconstruction: current versions, full-height
 * Overworld, every one-time migration already marked done. Bedrock derives the
 * same values when it initialises metadata for a chunk generated by the
 * current game, so this is what a 1.26 client would have written itself.
 */
export const CHUNK_META_DEFAULTS = {
  /** >= 1.16.0 -> uses the modern biome set. */
  biomeBaseGameVersion: "1.16.0",
  /** > 1.17.40 -> the Overworld has the extended -64..320 height range. */
  heightExtended: true,
  /** Applied at load time otherwise. */
  underwaterLavaLakeFixed: true,
  worldGenBelowZeroFixed: true,
  skullFlatteningPerformed: true,
  /** No neighbour-aware block upgrades are pending. */
  neighborAwareBlockUpgradeVersion: 0,
} as const;

/** Build the metadata compound for a world built from scratch at 1.26.51. */
export function buildChunkMetaData(input: ChunkMetaDataInput): Record<string, MetaTag> {
  const range = (): MetaTag => ({
    kind: "compound",
    value: {
      min: { kind: "short", value: input.dimensionRange.min },
      max: { kind: "short", value: input.dimensionRange.max },
    },
  });

  return {
    LastSavedBaseGameVersion: { kind: "string", value: input.baseGameVersion },
    OriginalBaseGameVersion: { kind: "string", value: input.baseGameVersion },
    BiomeBaseGameVersion: { kind: "string", value: CHUNK_META_DEFAULTS.biomeBaseGameVersion },
    DimensionName: { kind: "string", value: input.dimensionName },
    GenerationSeed: { kind: "long", value: input.generationSeed },
    GeneratorType: { kind: "int", value: input.generatorType },
    WorldGen1_18AppliedBelow0: { kind: "bool", value: true },
    Overworld1_18HeightExtended: { kind: "bool", value: CHUNK_META_DEFAULTS.heightExtended },
    BlendingVersion: { kind: "short", value: BLENDING_VERSION },
    OriginalDimensionHeightRange: range(),
    LastSavedDimensionHeightRange: range(),
    UnderwaterLavaLakeFixed: { kind: "bool", value: CHUNK_META_DEFAULTS.underwaterLavaLakeFixed },
    WorldGenBelowZeroFixed: { kind: "bool", value: CHUNK_META_DEFAULTS.worldGenBelowZeroFixed },
    SkullFlatteningPerformed: { kind: "bool", value: CHUNK_META_DEFAULTS.skullFlatteningPerformed },
    NeighborAwareBlockUpgradeVersion: {
      kind: "int",
      value: CHUNK_META_DEFAULTS.neighborAwareBlockUpgradeVersion,
    },
  };
}

/** Keys in the order the metadata compound is written and hashed. */
function sortedEntries(compound: Record<string, MetaTag>): Array<[string, MetaTag]> {
  return Object.keys(compound)
    .sort()
    .map((key): [string, MetaTag] => [key, compound[key]!]);
}

/** Tag ids per `MetaTag.kind`. */
const TAG_ID: Record<MetaTag["kind"], number> = {
  string: TAG.String,
  bool: TAG.Byte,
  short: TAG.Short,
  int: TAG.Int,
  long: TAG.Long,
  compound: TAG.Compound,
};

type BodyWriter = (w: ByteWriter, tag: MetaTag) => void;

/** How a flavour writes an NBT string's length prefix. */
type StringWriter = (w: ByteWriter, value: string) => void;

/** Disk NBT: u16 little-endian length. */
const writeStringDisk: StringWriter = (w, value) => w.str(value);

/** Network NBT: unsigned varint length. */
const writeStringNetwork: StringWriter = (w, value) => {
  const bytes = Buffer.from(value, "utf8");
  writeUnsignedVarint(w, BigInt(bytes.length));
  w.raw(bytes);
};

/** Write a tag body in the world's own (disk) little-endian NBT flavour. */
const writeBodyDisk: BodyWriter = (w, tag) => {
  switch (tag.kind) {
    case "string":
      w.str(tag.value);
      return;
    case "bool":
      w.u8(tag.value ? 1 : 0);
      return;
    case "short":
      w.i16le(tag.value);
      return;
    case "int":
      w.i32le(tag.value);
      return;
    case "long":
      w.i64le(tag.value);
      return;
    case "compound":
      for (const [key, child] of sortedEntries(tag.value)) {
        w.u8(TAG_ID[child.kind]);
        writeStringDisk(w, key);
        writeBodyDisk(w, child);
      }
      w.u8(TAG.End);
      return;
  }
};

function writeUnsignedVarint(w: ByteWriter, value: bigint): void {
  let n = value & 0xffffffffffffffffn;
  do {
    const b = Number(n & 0x7fn);
    n >>= 7n;
    w.u8(n ? b | 0x80 : b);
  } while (n);
}

/** Zig-zag signed varint, the encoding Bedrock uses for i32/i64 on the wire. */
function writeZigZagVarint(w: ByteWriter, value: bigint): void {
  const size = value < 0n || value > 0x7fffffffn ? 64 : 32;
  const shifted = size === 64 ? ((value << 1n) ^ (value >> 63n)) & 0xffffffffffffffffn : ((value << 1n) ^ (value >> 31n)) & 0xffffffffn;
  writeUnsignedVarint(w, shifted);
}

/**
 * Body writer for the hash input: the same compound serialized in Bedrock's
 * network order — varint string lengths and zig-zag varint i32/i64.
 */
const writeBodyNetwork: BodyWriter = (w, tag) => {
  switch (tag.kind) {
    case "string":
      writeStringNetwork(w, tag.value);
      return;
    case "bool":
      w.u8(tag.value ? 1 : 0);
      return;
    case "short":
      w.i16le(tag.value);
      return;
    case "int":
      writeZigZagVarint(w, BigInt(tag.value | 0));
      return;
    case "long":
      writeZigZagVarint(w, tag.value);
      return;
    case "compound":
      for (const [key, child] of sortedEntries(tag.value)) {
        w.u8(TAG_ID[child.kind]);
        writeStringNetwork(w, key);
        writeBodyNetwork(w, child);
      }
      w.u8(TAG.End);
      return;
  }
};

function writeNamedCompound(
  w: ByteWriter,
  compound: Record<string, MetaTag>,
  body: BodyWriter,
  writeString: StringWriter,
): void {
  w.u8(TAG.Compound);
  writeString(w, ""); // root name is always empty for chunk data
  for (const [key, tag] of sortedEntries(compound)) {
    w.u8(TAG_ID[tag.kind]);
    writeString(w, key);
    body(w, tag);
  }
  w.u8(TAG.End);
}

/** The metadata compound as stored on disk (Bedrock little-endian NBT). */
export function serializeMetaData(meta: Record<string, MetaTag>): Buffer {
  const w = new ByteWriter(512);
  writeNamedCompound(w, meta, writeBodyDisk, writeStringDisk);
  return w.toBuffer();
}

/**
 * The exact bytes Minecraft hashes: the same compound in Bedrock's *network*
 * order — varint string lengths, zig-zag varint i32/i64 — with its keys sorted.
 */
export function serializeMetaDataForHash(meta: Record<string, MetaTag>): Buffer {
  const w = new ByteWriter(512);
  writeNamedCompound(w, meta, writeBodyNetwork, writeStringNetwork);
  return w.toBuffer();
}

/** xxHash64 (seed 0) of the network-order metadata — the `MetaDataHash` value. */
export function hashChunkMetaData(meta: Record<string, MetaTag>): bigint {
  return Bun.hash.xxHash64(serializeMetaDataForHash(meta));
}

/** Write the `LevelChunkMetaDataDictionary` record for the given entries. */
export function serializeMetaDataDictionary(
  entries: ReadonlyArray<{ hash: bigint; meta: Record<string, MetaTag> }>,
): Buffer {
  const head = Buffer.allocUnsafe(4);
  head.writeUInt32LE(entries.length, 0);
  const parts: Buffer[] = [head];
  for (const entry of entries) {
    const hash = Buffer.allocUnsafe(8);
    hash.writeBigUInt64LE(entry.hash & 0xffffffffffffffffn, 0);
    parts.push(hash, serializeMetaData(entry.meta));
  }
  return Buffer.concat(parts);
}

/** An entry as read back out of the dictionary. */
export interface ParsedMetaDataEntry {
  hash: bigint;
  /** Raw NBT bytes of the metadata compound. */
  nbt: Buffer;
}

/** NBT tag payload sizes we can skip without decoding, per tag id. */
const FIXED_TAG_SIZE: Record<number, number> = {
  [TAG.Byte]: 1,
  [TAG.Short]: 2,
  [TAG.Int]: 4,
  [TAG.Long]: 8,
  [TAG.Float]: 4,
  [TAG.Double]: 8,
};

function readString(buf: Buffer, offset: number): { text: string; next: number } {
  const length = buf.readUInt16LE(offset);
  const start = offset + 2;
  return { text: buf.toString("utf8", start, start + length), next: start + length };
}

/** Skip one tag body, returning the offset just past it. */
function skipTagBody(buf: Buffer, offset: number, tagId: number): number {
  const fixed = FIXED_TAG_SIZE[tagId];
  if (fixed !== undefined) return offset + fixed;
  switch (tagId) {
    case TAG.String: {
      const length = buf.readUInt16LE(offset);
      return offset + 2 + length;
    }
    case TAG.ByteArray: {
      const length = buf.readInt32LE(offset);
      return offset + 4 + length;
    }
    case TAG.IntArray:
    case TAG.List: {
      throw new Error("metadata compounds are not expected to contain lists or int arrays");
    }
    case TAG.Compound: {
      let p = offset;
      for (;;) {
        const childId = buf.readUInt8(p++);
        if (childId === TAG.End) return p;
        p = readString(buf, p).next;
        p = skipTagBody(buf, p, childId);
      }
    }
    default:
      throw new Error(`cannot skip unknown NBT tag 0x${tagId.toString(16)}`);
  }
}

/** Read a `LevelChunkMetaDataDictionary` record back into its entries. */
export function parseMetaDataDictionary(buf: Buffer): ParsedMetaDataEntry[] {
  if (buf.length < 4) throw new Error("metadata dictionary is missing its entry count");
  const count = buf.readUInt32LE(0);
  const entries: ParsedMetaDataEntry[] = [];
  let p = 4;
  for (let i = 0; i < count; i++) {
    if (p + 8 > buf.length) throw new Error("metadata dictionary entry is truncated");
    const hash = buf.readBigUInt64LE(p);
    p += 8;
    const rootId = buf.readUInt8(p);
    if (rootId !== TAG.Compound) {
      throw new Error(`metadata entry ${i} starts with tag 0x${rootId.toString(16)}, not a compound`);
    }
    const start = p;
    p = readString(buf, p + 1).next;
    p = skipTagBody(buf, p, TAG.Compound);
    entries.push({ hash, nbt: buf.subarray(start, p) });
  }
  return entries;
}

/**
 * `BlendingData` (tag 0x40): not a blending source (`0`), saved with the
 * given blend version.
 */
export function serializeBlendingData(blendVersion = BLENDING_VERSION): Buffer {
  return Buffer.from([0, blendVersion & 0xff]);
}
