/**
 * Terrain: the wasteland itself.
 *
 * The Underworld is not a Nether clone. It is a *void world*: a torn plate of
 * grey and black rock floating in nothing, seamed with chasms that drop straight
 * into the void, soul-sand flats, sculk hollows, a powder-snow pocket, and a
 * nether-like lava reach on the far side. Nothing here is generated by the game;
 * every block in the realm is placed by this file and the area builders.
 */

import { P, type BlockState } from "./blocks.ts";
import { CONFIG, CHUNKS_X, WORLD_MAX_X, WORLD_MAX_Z, WORLD_MIN_X, WORLD_MIN_Z } from "./config.ts";
import { LANDMARKS, TERRAIN_REGIONS } from "./layout.ts";
import { fbm, hash2 } from "./noise.ts";
import type { World } from "./world.ts";

const R = CONFIG.terrain;

// ---------------------------------------------------------------------------
// Chasms and ravines
// ---------------------------------------------------------------------------

export interface Chasm {
  id: string;
  points: Array<{ x: number; z: number }>;
  /** Half width in blocks. */
  width: number;
  /** Wobble added to the width along the path. */
  wobble: number;
  /** true = the chasm is open to the void, false = a deep canyon with a floor. */
  toVoid: boolean;
}

/**
 * "Giant gaps of void", "deep chasms" and "cracks of void forming on the
 * ground" - the fractures that break the plate apart. The northern fracture and
 * the eastern ravine are crossed by the road network, which is where the map's
 * broken bridges come from.
 */
export const CHASMS: Chasm[] = [
  {
    // Shortened and narrowed so the eastern plate stays walkable and continuous.
    id: "eastFracture",
    points: [
      { x: 58, z: -160 },
      { x: 50, z: -80 },
      { x: 54, z: 0 },
      { x: 48, z: 80 },
    ],
    width: 3,
    wobble: 2,
    toVoid: true,
  },
  {
    // Narrower northern crack — still atmospheric but no longer severs the map.
    id: "northFracture",
    points: [
      { x: -90, z: -150 },
      { x: -30, z: -140 },
      { x: 30, z: -148 },
    ],
    width: 3,
    wobble: 2,
    toVoid: true,
  },
  {
    id: "parrotsRavine",
    points: [
      { x: 172, z: 10 },
      { x: 164, z: -46 },
      { x: 172, z: -100 },
    ],
    width: 5,
    wobble: 2,
    toVoid: false,
  },
  {
    id: "tombRavine",
    points: [
      { x: -128, z: 66 },
      { x: -150, z: 84 },
      { x: -176, z: 70 },
    ],
    width: 4,
    wobble: 2,
    toVoid: false,
  },
  // --- the expanded outer ring -------------------------------------------------
  {
    // A wide southern canyon with a magma floor, cut through the new range.
    id: "southCanyon",
    points: [
      { x: 18, z: 286 },
      { x: 52, z: 244 },
      { x: 90, z: 214 },
    ],
    width: 6,
    wobble: 3,
    toVoid: false,
  },
  {
    // A second void fracture in the far west, so the plate tears apart beyond the Citadel too.
    id: "farWestFracture",
    points: [
      { x: -232, z: 164 },
      { x: -266, z: 62 },
      { x: -238, z: -34 },
    ],
    width: 3,
    wobble: 2,
    toVoid: true,
  },
  {
    // A dry ravine across the new east highlands.
    id: "highlandRavine",
    points: [
      { x: 246, z: 150 },
      { x: 276, z: 96 },
      { x: 258, z: 30 },
    ],
    width: 4,
    wobble: 2,
    toVoid: false,
  },
];

const RAVINE_FLOOR_Y = 18;

// ---------------------------------------------------------------------------
// Shaping
// ---------------------------------------------------------------------------

interface ColumnInfo {
  land: boolean;
  surfaceY: number;
}

function distanceToSegment(px: number, pz: number, ax: number, az: number, bx: number, bz: number): number {
  const vx = bx - ax;
  const vz = bz - az;
  const wx = px - ax;
  const wz = pz - az;
  const len2 = vx * vx + vz * vz;
  const t = len2 === 0 ? 0 : Math.max(0, Math.min(1, (wx * vx + wz * vz) / len2));
  const dx = px - (ax + vx * t);
  const dz = pz - (az + vz * t);
  return Math.sqrt(dx * dx + dz * dz);
}

/** Distance from a point to a polyline, plus which segment it belongs to. */
function distanceToPath(x: number, z: number, points: Array<{ x: number; z: number }>): number {
  let best = Number.POSITIVE_INFINITY;
  for (let i = 0; i < points.length - 1; i++) {
    const a = points[i]!;
    const b = points[i + 1]!;
    const d = distanceToSegment(x, z, a.x, a.z, b.x, b.z);
    if (d < best) best = d;
  }
  return best;
}

export function chasmDistance(x: number, z: number): { toVoid: number; canyon: number } {
  let toVoid = Number.POSITIVE_INFINITY;
  let canyon = Number.POSITIVE_INFINITY;
  for (const chasm of CHASMS) {
    const d = distanceToPath(x, z, chasm.points);
    const wobble = (fbm(x, z, CONFIG.seed + 401, { octaves: 2, frequency: 1 / 12 }) - 0.5) * 2 * chasm.wobble;
    const edge = d + wobble - chasm.width;
    if (chasm.toVoid) toVoid = Math.min(toVoid, edge);
    else canyon = Math.min(canyon, edge);
  }
  return { toVoid, canyon };
}

function superellipseDistance(x: number, z: number, radius: number): number {
  const nx = Math.abs(x) / radius;
  const nz = Math.abs(z) / radius;
  return Math.pow(Math.pow(nx, 4) + Math.pow(nz, 4), 0.25);
}

export function sampleColumn(x: number, z: number): ColumnInfo {
  // -- landmass --------------------------------------------------------------
  const edgeNoise = (fbm(x, z, CONFIG.seed + 7, { octaves: 3, frequency: 1 / 56 }) - 0.5) * 0.2;
  let land = superellipseDistance(x, z, R.realmRadius) + edgeNoise < 1;

  // -- the western void gulf -------------------------------------------------
  // Narrower gulf + less noisy edges so the plate stays more continuous.
  const gulf = R.voidGulf;
  const gulfEdgeNoise = (fbm(x, z, CONFIG.seed + 13, { octaves: 3, frequency: 1 / 26 }) - 0.5) * 6;
  if (x + gulfEdgeNoise > gulf.minX && x + gulfEdgeNoise < gulf.maxX) land = false;

  // -- chasms ---------------------------------------------------------------
  const { toVoid, canyon } = chasmDistance(x, z);
  if (toVoid < 0) land = false;

  // -- height ---------------------------------------------------------------
  const relief = fbm(x, z, CONFIG.seed + 21, { octaves: 4, frequency: 1 / 96 });
  let amplitude = R.reliefAmplitude;
  let delta = 0;
  let ridgedBoost = 0;

  for (const region of TERRAIN_REGIONS) {
    const inside =
      region.shape.kind === "circle"
        ? Math.hypot(x - region.shape.x, z - region.shape.z) <= region.shape.radius
        : x >= region.shape.x1 && x <= region.shape.x2 && z >= region.shape.z1 && z <= region.shape.z2;
    if (!inside) continue;
    if (region.id === "gulf") continue; // handled above
    delta += region.heightDelta ?? 0;
    if (region.relief !== undefined) amplitude *= region.relief;
    if (region.ridged) {
      ridgedBoost += fbm(x, z, CONFIG.seed + 33, { octaves: 3, frequency: 1 / 58, ridged: true }) * 12;
    }
  }

  let surfaceY = R.baseHeight + (relief - 0.5) * 2 * amplitude + delta + ridgedBoost;

  // Rim falloff: gentle taper so cliffs still exist but the plate doesn't
  // disintegrate into floating scraps near the edge.
  const edgeFactor = superellipseDistance(x, z, R.realmRadius);
  if (edgeFactor > 0.90 && land) {
    const t = Math.min(1, (edgeFactor - 0.90) / 0.10);
    surfaceY -= t * t * 14;
  }

  // -- canyon carve (ravines keep a floor instead of opening to the void) ----
  if (canyon < 0 && land) {
    surfaceY = Math.min(surfaceY, RAVINE_FLOOR_Y + Math.max(0, canyon + 8) * 1.5);
  }

  return { land, surfaceY: Math.round(surfaceY) };
}

// ---------------------------------------------------------------------------
// Material painting
// ---------------------------------------------------------------------------

function inCircle(x: number, z: number, cx: number, cz: number, radius: number): boolean {
  const dx = x - cx;
  const dz = z - cz;
  return dx * dx + dz * dz <= radius * radius;
}

/**
 * How dark the wasteland gets toward the dark edge.
 *
 * Canon: "the sky and void grow increasingly darker as the proximity to the end
 * shortens." The gradient therefore covers the *whole* western reach - it opens
 * west of the Center, is plainly black over the void castles, and is at its
 * darkest beyond the Citadel - instead of only the last sliver of rim. The
 * value is 0 everywhere east of `darkEdgeStartX` and 1 at `darkEdgeX`.
 *
 * Exported because the ruin masonry darkens with it: the broken structures out
 * west are built from the same black rock the ground there is made of.
 */
export function darkness(x: number): number {
  const t = (R.darkEdgeStartX - x) / (R.darkEdgeStartX - R.darkEdgeX);
  return Math.max(0, Math.min(1, t));
}

function voidFloorBlock(x: number, z: number): BlockState {
  const n = hash2(x, z, CONFIG.seed + 91);
  if (n < 0.25) return P.obsidian;
  if (n < 0.5) return P.basalt;
  if (n < 0.8) return P.deepslate;
  return P.cobbledDeepslate;
}

/** Surface block for a column, driven by region + noise patches. */
export function surfaceBlock(x: number, z: number, y: number): BlockState {
  const seed = CONFIG.seed;

  // Frost pocket.
  if (inCircle(x, z, LANDMARKS.frostPocket.center.x, LANDMARKS.frostPocket.center.z, 44)) {
    const n = hash2(x, z, seed + 300);
    if (n < 0.1) return P.powderSnow;
    if (n < 0.24) return P.snowBlock;
    if (n < 0.34) return P.ice;
    return P.snowLayer;
  }

  // The ashen reaches / lava reach: nether-like rock, but sparse - never a
  // full Nether biome.
  if (inCircle(x, z, LANDMARKS.ashenReaches.center.x, LANDMARKS.ashenReaches.center.z, 62)) {
    const n = hash2(x, z, seed + 310);
    if (n < 0.42) return P.blackstone;
    if (n < 0.6) return P.basalt;
    if (n < 0.72) return P.netherrack;
    if (n < 0.8) return P.magma;
    if (n < 0.9) return P.smoothBasalt;
    return P.polishedBlackstone;
  }

  // Sculk hollow around the tomb.
  const tomb = LANDMARKS.tomb.center;
  if (inCircle(x, z, tomb.x, tomb.z, 70)) {
    const n = hash2(x, z, seed + 320);
    if (n < 0.22) return P.sculk;
    if (n < 0.28) return P.soulSoil;
  }

  // Soul flats.
  const soul = fbm(x, z, seed + 41, { octaves: 3, frequency: 1 / 34 });
  if (soul > 0.62) {
    const n = hash2(x, z, seed + 411);
    return n < 0.55 ? P.soulSand : P.soulSoil;
  }

  const d = darkness(x);
  const n = hash2(x, z, seed + 500);

  // Blackstone outcrops become common in the dark west.
  if (n < 0.18 + d * 0.42) {
    const m = hash2(x, z, seed + 501);
    if (d > 0.55 && m < 0.16) return P.cryingObsidian;
    if (m < 0.55) return P.blackstone;
    if (m < 0.75) return P.polishedBlackstone;
    return P.basalt;
  }
  if (n < 0.34) return P.cobbledDeepslate;
  if (n < 0.42) return P.tuff;
  if (n < 0.46) return P.gravel;
  if (n < 0.47) return P.obsidian;
  if (d > 0.6 && n > 0.9) return P.blackConcrete;
  if (n > 0.97) return P.chiseledDeepslate;
  return P.deepslate;
}

function subSurfaceBlock(x: number, y: number, z: number, surfaceY: number, depth: number): BlockState {
  if (y <= depth + 1) return voidFloorBlock(x, z);
  const n = hash2(x * 3 + y, z * 7 - y, CONFIG.seed + 600);
  if (n < 0.22) return P.tuff;
  if (n < 0.3) return P.gravel;
  if (n < 0.36) return P.blackstone;
  if (n > 0.965 && surfaceY - y > 4) return P.goldOre;
  return P.deepslate;
}

// ---------------------------------------------------------------------------
// Generation
// ---------------------------------------------------------------------------

export interface TerrainStats {
  landColumns: number;
  voidColumns: number;
  minY: number;
  maxY: number;
}

export function generateTerrain(world: World): TerrainStats {
  const stats: TerrainStats = { landColumns: 0, voidColumns: 0, minY: 999, maxY: 0 };

  for (let z = WORLD_MIN_Z; z <= WORLD_MAX_Z; z++) {
    for (let x = WORLD_MIN_X; x <= WORLD_MAX_X; x++) {
      const { land, surfaceY } = sampleColumn(x, z);
      world.setLand(x, z, land);
      world.setSurface(x, z, surfaceY);
      if (!land) {
        stats.voidColumns++;
        continue;
      }
      stats.landColumns++;
      if (surfaceY < stats.minY) stats.minY = surfaceY;
      if (surfaceY > stats.maxY) stats.maxY = surfaceY;

      const taperNoise = fbm(x, z, CONFIG.seed + 700, { octaves: 2, frequency: 1 / 40 });
      const depth = Math.max(3, Math.round(R.plateDepth + (taperNoise - 0.5) * 16));
      const bottom = Math.max(0, surfaceY - depth);

      for (let y = bottom; y <= surfaceY; y++) {
        let block: BlockState;
        if (y === surfaceY) block = surfaceBlock(x, z, y);
        else if (y >= surfaceY - 3) {
          const s = surfaceBlock(x, z, y);
          block = s.name === "minecraft:snow_layer" || s.name === "minecraft:powder_snow" ? P.snowBlock : s;
        } else {
          block = subSurfaceBlock(x, y, z, surfaceY, bottom);
        }
        world.set(x, y, z, block);
      }
    }
  }

  fillLavaLake(world);
  return stats;
}

/** The lava lake Parrot's crew sails across, with the strider island in it. */
function fillLavaLake(world: World): void {
  const lake = LANDMARKS.ashenReaches.center;
  const radius = 42;
  const islandRadius = 13;
  const lavaLevel = R.baseHeight - 6;

  for (let z = lake.z - radius; z <= lake.z + radius; z++) {
    for (let x = lake.x - radius; x <= lake.x + radius; x++) {
      if (!world.inRealm(x, z)) continue;
      const d = Math.hypot(x - lake.x, z - lake.z);
      const warp = (fbm(x, z, CONFIG.seed + 800, { octaves: 3, frequency: 1 / 30 }) - 0.5) * 16;
      const edge = d + warp;
      if (edge > radius) continue;

      // The strider island: a raised mound in the middle of the lake.
      if (d < islandRadius + warp * 0.4) {
        const h = lavaLevel + 4 + Math.round((1 - d / islandRadius) * 3);
        world.setSurface(x, z, h);
        world.setLand(x, z, true);
        for (let y = lavaLevel - 6; y <= h; y++) {
          world.set(x, y, z, y === h ? P.blackstone : y > lavaLevel ? P.basalt : P.magma);
        }
        continue;
      }

      // Shore ring rises toward the lava mountains; the lake itself is a shallow
      // bowl of lava that never reaches the plate underside.
      const shore = Math.max(0, edge - (radius - 8));
      const target = Math.round(lavaLevel - 2 + shore * 0.6);
      if (target < lavaLevel) {
        for (let y = lavaLevel - 8; y < lavaLevel; y++) world.set(x, y, z, y === lavaLevel - 8 ? P.magma : P.basalt);
        world.set(x, lavaLevel, z, P.lava);
        world.setLand(x, z, true);
        world.setSurface(x, z, lavaLevel);
      } else {
        for (let y = lavaLevel - 8; y <= target; y++) {
          world.set(x, y, z, y === target ? (hash2(x, z, CONFIG.seed + 810) < 0.3 ? P.magma : P.basalt) : P.basalt);
        }
        world.setLand(x, z, true);
        world.setSurface(x, z, target);
      }
    }
  }
}

/** Flood-fills the chasms so their walls read as sheer rock instead of noise. */
export function carveChasmWalls(world: World): void {
  for (const chasm of CHASMS) {
    for (let i = 0; i < chasm.points.length - 1; i++) {
      const a = chasm.points[i]!;
      const b = chasm.points[i + 1]!;
      const steps = Math.ceil(Math.hypot(b.x - a.x, b.z - a.z)) * 2;
      for (let s = 0; s <= steps; s++) {
        const t = s / steps;
        const cx = a.x + (b.x - a.x) * t;
        const cz = a.z + (b.z - a.z) * t;
        for (let dz = -chasm.width - chasm.wobble; dz <= chasm.width + chasm.wobble; dz++) {
          for (let dx = -chasm.width - chasm.wobble; dx <= chasm.width + chasm.wobble; dx++) {
            const x = Math.round(cx + dx);
            const z = Math.round(cz + dz);
            if (!world.inRealm(x, z)) continue;
            if (world.isLand(x, z)) continue;
            const surface = world.surfaceAt(x, z);
            // Leave a lip of rock on the chasm walls so the fracture has an edge.
            const d = distanceToPath(x, z, chasm.points);
            if (d > chasm.width) continue;
            for (let y = Math.max(0, surface - 4); y <= surface + 2; y++) {
              world.set(x, y, z, y > surface - 2 ? P.cobbledDeepslate : P.deepslate);
            }
          }
        }
      }
    }
  }
}
